<!doctype html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<div class="EXPLORE-THE-WORLD-OF">
		<h3>EXPLORE THE WORLD OF COMPOUND MICROSCOPES</h3>
	</div>
	<div class="Taking-design">
		<p>Taking design cues from the popular M10L Series, the non-digital M10 compound microscope series expands your options. Ideal for higher education and professional applications</p>
	</div>
	
	<div class="View-Products">
	
		<h5>SHOP PRODUCTS<div class="a"/></h5>
		
	</div>
	
	
	
	
	
	<div class="Related-Product-Carousel">
		<div class="Rectangle" id="products-1">
			<img src="images/products1.png" alt="">
			<p>Binocular Cordless LED Microscope - M3-B</p>
			<h5>was US$ 1,999.00</h5>
			<h6>US$ 1,799.00<h6>
		</div>
		<div class="Rectangle" id="products-2">
			<img src="images/products2.png" alt="">
			<p>Trinocular Corded Halogen Microscope - M15T-P</p>
			<h6>US$ 1,999.00<h6>
		</div>
		<div class="Rectangle" id="products-3">
			<img src="images/products3.png" alt="">
			<p>Digital Monocular Microscope with 3MP Camera - M2252DGL</p>
			<h5>was US$ 1,999.00</h5>
			<h6>US$ 1,799.00<h6>
		</div>
		<div class="Rectangle" id="products-4">
			<img src="images/products4.png" alt="">
			<p>Digital Monocular Microscope with 3MP Camera - M2252DGL</p>
			<h6>US$ 1,999.00<h6>
		</div>
	</div>
</body>
</html>
