<div class="content_top">
    <form>
        <h1>HELLO. HOW CAN WE HELP?</h1>
        <h1>CONTACT WITH US</h1>
    </form>
</div>

<div class="content_left">
    <form>
        Name
        <input type="text" name="name" placeholder="Name"><br>
        Email address
        <input type="text" name="email" placeholder="testcontactus@gmail.com"><br>
        Phone Number
        <input type="number" name="phone" placeholder="Phone"><br>
        Message
        <input type="text" name="message" placeholder="Message"><br>
        Please type the letters below
        <input type="text" name="letters"><br>
        <img src="http://wsoftpro.com/pub/media/captcha/base/e44bff386b7f0fc390264ae4038d9472.png">
        <input type="submit" value="Reload captcha"><br>
        <input type="submit" value="SEND YOUR MESSAGE" >
    </form>
</div>


<div class="content_right">
    <h3>Nice to hear You!</h3>
    <p>Wsoftpro is a specialized ecommerce agency that offers full service ecommerce solution to customer all over the
        globe. Starting from 2012, we have achieved outstanding results in building online retail websites, boosting the
        sites’ traffic and conversion rate.</p>
    <h3>Contact Information</h3>

    <h4>Business Hours</h4>

    <p>ThemeMakers Support team is available from Monday to Friday 9 a.m. – 6 p.m. (GMT +1)</p>
    <p>Saturday: Closed</p>
    <p>Sunday: Closed</p>

    <h4>Address</h4>

    <p>Room 2701, VNT Tower, 19 Nguyen Trai Street, Thanh Xuan District, Hanoi.</p>
    <p>Call: +84 169 3558941</p>
    <p>Block 233 Bain Street, S180233</p>
    <p>Call: +65 82390498</p>

    <h4>You Can Reach us via</h4>

    <p>Phone: +84 169 3558941</p>
    <p>Support ticket system: https://wsoftpro.com</p>
    <p>Support forum: https://wsoftpro.com</p>
</div>