<div class="footer-page">
    <div class="about_us">
        <h5>ABOUT US</h5>
        <ul>
            <li>Our Story</li>
            <li>Our Store</li>
            <li>Testimonlals</li>
            <li>Contact US</li>
        </ul>
    </div>

    <div class="shop_toys">
        <h5>SHOP TOYS</h5>
        <ul>
            <li>Category</li>
            <li>Age</li>
            <li>Gender</li>
            <li>Brand</li>
            <li>Gift Card</li>
            <li>Sale</li>
        </ul>
    </div>

    <div class="account">
        <h5>ACCOUNT</h5>
        <ul>
            <li>Login/ Register</li>
            <li>My Account</li>
            <li>My Cart</li>
            <li>Whishlish</li>
            <li>Orders and Returns</li>
            <li>Gift Card</li>
        </ul>
    </div>

    <div class="customer_service">
        <h5>CUSTOMER SERVICE</h5>
        <ul>
            <li>FAQs</li>
            <li>Deleverles</li>
            <li>Returns & Cancellations</li>
            <li>Reward Points</li>
            <li>Custom Greeting Cards Wrapping</li>
            <li>Sales Terms and Conditions</li>
            <li>Redeeming Gift Card</li>
            <li>Payment Security</li>
        </ul>
    </div>


    <form class="newsletter">
        <h5>NEWSLETTER</h5>
        <h6>SUBSCRIBE & SAVE 10%</h6>
        <input type="search" placeholder="Your Email" />
        <h5>FOLLOW US</h5>
        <script></script>
    </form>
</div>

<div class="copyright">
    <p>Copyright </p>
</div>